Repository epitech-mirroring/ArcadeShared, pull requests merged in 2024-03, with the labels that each got.

#3 🧱 Basic architecture
  .gitignore
  IArcade.hpp
  IDriver.hpp
  IGame.hpp
  displayable/IDisplayable.hpp
  displayable/entities/IEntity.hpp
  displayable/entities/ISprite.hpp
  displayable/primitives/ICircle.hpp
  displayable/primitives/IPrimitive.hpp
  displayable/primitives/ISquare.hpp
  events/IEvent.hpp
  events/Keys.hpp
  utils/IColor.hpp
  utils/ICoordinate.hpp
  utils/IPicture.hpp
Labels: enhancement

#10 :art: Rotation handler
  utils/ICanRotate.hpp
  utils/IPicture.hpp
Labels: enhancement

#8 :goal_net: create error handler interface
  errors/IDriverError.hpp
  errors/IError.hpp
  errors/IGameError.hpp
Labels: enhancement

#13 ♻️ Refactor some functions
  displayable/IDisplayable.hpp
  displayable/entities/IEntity.hpp
  displayable/entities/ISprite.hpp
  displayable/primitives/IPrimitive.hpp
  errors/IDriverError.hpp
  errors/IGameError.hpp
  events/IEvent.hpp
  utils/ICanRotate.hpp
  utils/ICoordinate.hpp
  utils/IPicture.hpp
Labels: bug, breaking changes

#12 :art: Add IText interface for text implementation
  displayable/primitives/IText.hpp
Labels: enhancement

#14 :bug: Add missing pragma once
  errors/IDriverError.hpp
  errors/IError.hpp
  errors/IGameError.hpp
Labels: bug

#16 :memo: Update README to explain the extern 'C' structure
  README.md
Labels: documentation

#17 💥 Missing virtual
  IGame.hpp
  displayable/IDisplayable.hpp
  displayable/entities/IEntity.hpp
  displayable/entities/ISprite.hpp
  displayable/primitives/ICircle.hpp
  displayable/primitives/IPrimitive.hpp
  displayable/primitives/ISquare.hpp
  displayable/primitives/IText.hpp
  errors/IDriverError.hpp
  errors/IError.hpp
  errors/IGameError.hpp
  events/IEvent.hpp
  utils/ICanRotate.hpp
  utils/IColor.hpp
  utils/ICoordinate.hpp
  utils/IPicture.hpp
Labels: bug, breaking changes

#19 :sparkles: Add function to specify preferred size
  IArcade.hpp
  IDriver.hpp
Labels: enhancement

#20 :recycle: Add or Remove smart pointers based on context
  IArcade.hpp
  IDriver.hpp
  IGame.hpp
  displayable/IDisplayable.hpp
  displayable/entities/IEntity.hpp
  displayable/entities/ISprite.hpp
  displayable/primitives/ICircle.hpp
  displayable/primitives/IPrimitive.hpp
  displayable/primitives/ISquare.hpp
  errors/IDriverError.hpp
  errors/IGameError.hpp
  events/IEvent.hpp
Labels: enhancement, breaking changes
