Repository epitech-mirroring/ArcadeShared, pull requests merged in 2024-04, with the labels that each got.

#21 ✨ Improvements and small fixes
  IDriver.hpp
  IGame.hpp
  displayable/IDisplayable.hpp
  displayable/entities/ISprite.hpp
  displayable/primitives/IPrimitive.hpp
  displayable/primitives/IText.hpp
  events/IEvent.hpp
  events/Keys.hpp
  utils/IPicture.hpp
Labels: enhancement, breaking changes

#24 :bug: Resolve conflict between the names of our EventKey and the names of the ncurses key
  errors/IDriverError.hpp
  errors/IGameError.hpp
  events/IEvent.hpp
  events/Keys.hpp
Labels: bug, enhancement

#25 🎨 Debug gizmos
  IArcade.hpp
  ICanDrawGizmos.hpp
  displayable/primitives/ILine.hpp
  displayable/primitives/ISquare.hpp
  events/Keys.hpp
Labels: enhancement

#28 :art: Add color support to IDisplayable interface
  displayable/IDisplayable.hpp
  displayable/primitives/IPrimitive.hpp
Labels: enhancement

#29 ✨ Add missing score function and small time function
  IArcade.hpp
Labels: enhancement
